name = "digipay"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

# Environment configuration for Pages (only preview and production are supported)
[env.production]
name = "digipay"

[env.production.vars]
NODE_ENV = "production"
NUXT_PUBLIC_NOTION_TOKEN = "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"
NUXT_PUBLIC_NOTION_DATABASE_ID = "15795c325fa780f2939add8bb30d4b36"
NUXT_PUBLIC_NOTION_SPEAKERS_DB_ID = "16395c325fa780e4bf5ff50481f0662e"
NUXT_PUBLIC_NOTION_CONTACTS_DATABASE_ID = "16895c325fa780029522cf19408637b3"
NUXT_PUBLIC_NOTION_NEWSLETTER_DATABASE_ID = "1f995c325fa7805ba4d9e0d6415a34bd"


[env.preview]
name = "digipay-preview"

[env.preview.vars]
NODE_ENV = "preview"
NUXT_PUBLIC_NOTION_TOKEN = "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"
NUXT_PUBLIC_NOTION_DATABASE_ID = "15795c325fa780f2939add8bb30d4b36"
NUXT_PUBLIC_NOTION_SPEAKERS_DB_ID = "16395c325fa780e4bf5ff50481f0662e"
NUXT_PUBLIC_NOTION_CONTACTS_DATABASE_ID = "16895c325fa780029522cf19408637b3"
NUXT_PUBLIC_NOTION_NEWSLETTER_DATABASE_ID = "1f995c325fa7805ba4d9e0d6415a34bd"


# Variables
[vars]
NODE_ENV = "production"
NUXT_PUBLIC_NOTION_TOKEN = "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"
NUXT_PUBLIC_NOTION_DATABASE_ID = "15795c325fa780f2939add8bb30d4b36"
NUXT_PUBLIC_NOTION_SPEAKERS_DB_ID = "16395c325fa780e4bf5ff50481f0662e"
NUXT_PUBLIC_NOTION_CONTACTS_DATABASE_ID = "16895c325fa780029522cf19408637b3"
NUXT_PUBLIC_NOTION_NEWSLETTER_DATABASE_ID = "1f995c325fa7805ba4d9e0d6415a34bd"
